model:
  scale_factor: 1.0 #1.15258426  0.25
  disable_first_stage_autocast: true
  latent_input: false
  subjects_input: true
  subject_cond_dropout: 0
  log_keys:
    - txt
  
  denoiser_config:
    target: sgm.modules.diffusionmodules.denoiser.Denoiser
    params:
      weighting_config:
        target: sgm.modules.diffusionmodules.denoiser_weighting.EpsWeighting
      scaling_config:
        target: sgm.modules.diffusionmodules.denoiser_scaling.RFScaling

  network_config:
    target: dit_video_crossattn.DiffusionTransformer
    params:
      # num_classes: sequential
      time_freq_dim: 256
      time_embed_dim: 5120
      share_adaln: True
      elementwise_affine: False
      num_frames: 81
      time_compressed_rate: 4
      latent_width: 800
      latent_height: 800
      num_layers: 40
      patch_size: [1, 2, 2]
      in_channels: 16
      out_channels: 16
      text_dim: 4096
      hidden_size: 5120
      inner_hidden_size: 13824
      # adm_in_channels: 1152
      num_attention_heads: 40
      use_SwiGLU: False
      use_RMSNorm: False
      layernorm_epsilon: 1e-6
      max_subject_nums: 3
      end_concat: False
      fsdp2: True

      transformer_args:
        checkpoint_activations: True
        vocab_size: 1
        max_sequence_length: 64
        layernorm_order: pre
        skip_init: false
        model_parallel_size: 1
        is_decoder: True

      modules:
        pos_embed_config:
          target: dit_video_crossattn.Rotary3DPositionEmbeddingMixin
          params:
            hidden_size_head: 128
            interleaved_rope: True
            shiftT: True #false代表image的t都相同，暂时不要这么设置，因为代码未适配
            shiftW: True
            shiftH: True
            overloop: True # 是否堆叠image states的rope， true则hw不变，only change t，false则hw都改变
            max_w: 80
            max_h: 80 # max w or h /8 / 2
            rope_continue: False # 是否连续的rope，true则不连续，false则连续
            
        patch_embed_config:
          target: dit_video_crossattn.ImagePatchEmbeddingMixin
          params:
            use_conv: True

        adaln_layer_config:
          target: dit_video_crossattn.AdaLNMixin
          params:
            qk_ln: True
            qk_ln_affine: True
            hidden_size_head: 5120
            subject2video: True
            new_adaln: False
            image_cross_text: True

        final_layer_config:
          target: dit_video_crossattn.FinalLayerMixin

  conditioner_config:
    target: sgm.modules.GeneralConditioner
    params:
      emb_models:
        # crossattn cond
          - is_trainable: false
            input_key: txt
            ucg_rate: 0.1 
            legacy_ucg_val: ""
            target: sgm.modules.encoders.umt5.T5EncoderModel
            params:
              checkpoint_path: Kaleido-14B-S2V/umt5-xxl/models_t5_umt5-xxl-enc-bf16.pth
              tokenizer_path: Kaleido-14B-S2V/umt5-xxl
              max_length: 512

      #     - is_trainable: false
      #       input_key: txt
      #       ucg_rate: 0
      #       target: sgm.modules.encoders.modules.FrozenSiglipEmbedder
      #       params:
      #         cache_dir: /workspace/ckpt/official_pretrains/
      # cor_embs: [0, 1]
      # cor_p: [0.9, 0, 0, 0.1] # 对应于:00, 10, 01, 11, 1表示用uncond, 0表示用cond

  first_stage_config:
    target : sgm.models.wan_vae.WanVAE
    params:
      vae_pth: Kaleido-14B-S2V/Wan2.1_VAE.pth
      dtype: torch.bfloat16

  loss_fn_config:
    target: sgm.modules.diffusionmodules.loss.RFLoss
    params:
      schedule_shift: True
      dropImage: False
      sigma_sampler_config:
        target: sgm.modules.diffusionmodules.sigma_sampling.RFSampling
        params:
          p_mean: 0.0
          p_std: 1.0

  sampler_config:
    target: sgm.modules.diffusionmodules.sampling.RFSampler
    params:
      mode: normal
      schedule_shift: False
      hunyuan_schedule: True
      num_steps: 50
      verbose: True

      discretization_config:
        target: sgm.modules.diffusionmodules.discretizer.RFDiscretization
        params:
          reverse: False

      guider_config:
        target: sgm.modules.diffusionmodules.guiders.VanillaCFG
        params:
          scale: 6